### ISSUE TITLE
欢迎吐槽和指点

### ISSUE THREAD

**Issue by hihozhou** [hihozhou/php-opencv#1]
欢迎吐槽和指点 ~

**Comment by yanhuixie** [comment]
挖～ 可惜我只是来点赞的。。：D

**Comment by yanhuixie** [comment]
目前进度是？全部API都翻译完了，等待进一步文档化？

**Comment by hihozhou** [comment]
@yanhuixie 现在还在开发基础部分

**Comment by weijer** [comment]
666 php 又有了新领域

**Comment by hihozhou** [comment]
现在已经可以进行LBPH人脸识别了

**Comment by bendan365** [comment]
我的环境，opencv是3.3.0版本，但编译的时候，提示这个错误，说找不到文件“opencv2/face.hpp”
请问，要怎么处理呢
/data/install/php-opencv/source/opencv2/opencv_face.h:22:28: fatal error: opencv2/face.hpp: No such file or directory
compilation terminated.
Makefile:194: recipe for target 'opencv.lo' failed
make: *** [opencv.lo] Error 1

**Comment by hihozhou** [comment]
@bendan365 时候有共同编译opencv_contrib？

**Comment by bendan365** [comment]
没有，要怎样调整呢

**Comment by bendan365** [comment]
编译成功了，但执行以下代码时，nginx提示异常
<?php if (!extension_loaded("opencv")) print "skip"; ?>
<?php
        use function CV\{ imread, imshow, waitkey, namedWindow};
        $im = imread('/data/web/public/Obama.png');//load image
        namedWindow('This is Obama id card',WINDOW_FULLSCREEN);//create window
        imshow('This is Obama id card',$im);//show image on window
        waitkey(0);
?>
异常信息：
`2017/08/07 12:03:25 [error] 96039#0: *563554 recv() failed (104: Connection reset by peer) while reading response header from upstream`
运行环境：nginx，php-fpm(php7)

**Comment by bendan365** [comment]
编译成功了，但执行以下代码时，nginx提示异常
![qq 20170807120728](https://user-images.githubusercontent.com/3345783/29011880-4d424f58-7b69-11e7-8401-ba9a1eae5d6e.png)

异常信息：
2017/08/07 12:03:25 [error] 96039#0: *563554 recv() failed (104: Connection reset by peer) while reading response header from upstream
运行环境：nginx，php-fpm(php7)

**Comment by bendan365** [comment]
执行以下代码，提示没有定义WINDOW_FULLSCREEN
![111](https://user-images.githubusercontent.com/3345783/29011974-31d03c8e-7b6a-11e7-8a66-c309a1de52c5.png)

![22222](https://user-images.githubusercontent.com/3345783/29011991-562a2f72-7b6a-11e7-8a1b-1913c9f2a7f0.png)

**Comment by hihozhou** [comment]
@bendan365 
```php
use const CV\WINDOW_FULLSCREEN;
```

**Comment by bendan365** [comment]
我没看清楚文档，就想当然的在nginx环境下运行了，原来是要在cli模式下的，看到效果了，赞

**Comment by bendan365** [comment]
LBPH，有没demo啊

**Comment by yanhuixie** [comment]
@bendan365 你可以试试直接百度／Google LBPH，会找到很多C++、Python的代码，参照PHP的接口翻译一下就好了。一般C++的代码比较普遍也容易翻译，Python的代码大多用到了Numpy或Pandas之类的高阶库，不好翻译。不过思路都是很清楚的，另外，LBPH应该有opencv官方demo代码。

**Comment by hihozhou** [comment]
@bendan365 ,和yanhuixie说的差不多,在1.0的版本,主要在功能上实现,php会尽量和C++版本的风格相同,在2.0的版本会进行代码简单优雅风格。至于LBPH部分的demo我迟点整理一下上传上来，并在会在写上文档

**Comment by imjakey** [comment]
ubuntu 16.04 下 缺少 libqt4 导致cmake失败， 建议在文档里面的安装前准备里面加上

 sudo apt-get install libqt4-dev qt4-dev-tools

另外文档编辑地址是无效的：
https://github.com/hexojs/site/edit/master/source/zh-cn/docs/install.md

谢谢！

**Comment by hihozhou** [comment]
@imjakey 感谢反馈，关于qt的原因我也未去测试，但是在ubuntu14下是可以的，但是用的是cmake高版本。具体是系统还是cmake版本问题我要测试后才知道

**Comment by MaleicAcid** [comment]
sudo apt-add-repository ppa:canonical-qt5-edgers/ubuntu1204-qt5
sudo apt-get update
sudo sudo apt-get install qt5-default

我是这样装qt的

**Comment by brianboy** [comment]
/root/php-opencv/source/opencv2/face/opencv_facemarkLBF.cc:32:9: error: 'FacemarkLBF' was not declared in this scope
     Ptr<FacemarkLBF> Facemark;
         ^
/root/php-opencv/source/opencv2/face/opencv_facemarkLBF.cc:32:20: error: template argument 1 is invalid
     Ptr<FacemarkLBF> Facemark;
                    ^
/root/php-opencv/source/opencv2/face/opencv_facemarkLBF.cc: In function 'void zim_opencv_facemark_lbf_create(zend_execute_data*, zval*)':
/root/php-opencv/source/opencv2/face/opencv_facemarkLBF.cc:55:21: error: 'FacemarkLBF' has not been declared
     obj->Facemark = FacemarkLBF::create();
                     ^
/root/php-opencv/source/opencv2/face/opencv_facemarkLBF.cc: In function 'void zim_opencv_facemark_lbf_loadModel(zend_execute_data*, zval*)':
/root/php-opencv/source/opencv2/face/opencv_facemarkLBF.cc:67:18: error: base operand of '->' is not a pointer
     obj->Facemark->loadModel(filename);
                  ^
/root/php-opencv/source/opencv2/face/opencv_facemarkLBF.cc: In function 'void zim_opencv_facemark_lbf_getFaces(zend_execute_data*, zval*)':
/root/php-opencv/source/opencv2/face/opencv_facemarkLBF.cc:81:18: error: base operand of '->' is not a pointer
     obj->Facemark->getFaces(*(image_object->mat), objects);
                  ^
/root/php-opencv/source/opencv2/face/opencv_facemarkLBF.cc: In function 'void zim_opencv_facemark_lbf_fit(zend_execute_data*, zval*)':
/root/php-opencv/source/opencv2/face/opencv_facemarkLBF.cc:135:18: error: base operand of '->' is not a pointer
     obj->Facemark->fit(*(image_object->mat), faces, landmarks);
                  ^
/root/php-opencv/source/opencv2/face/opencv_facemarkLBF.cc: In function 'void opencv_facemark_lbf_free_obj(zend_object*)':
/root/php-opencv/source/opencv2/face/opencv_facemarkLBF.cc:195:17: error: type 'int' argument given to 'delete', expected pointer
     delete obj->Facemark;
                 ^

**Comment by brianboy** [comment]
环境是centos7 php7.2
