### ISSUE TITLE
Error on Make. How I resolve it?

### ISSUE THREAD

**Issue by wellton** [hihozhou/php-opencv#11]
![captura de tela em 2017-09-19 16-45-38](https://user-images.githubusercontent.com/2234645/30612152-0270e382-9d5a-11e7-9ddc-700a38e9857f.png)

**Comment by hihozhou** [comment]
Extensions now need to install opencv_contrib for a while, and later determine if the computer opencv has opencv_contrib to load the corresponding code.
https://github.com/opencv/opencv_contrib

**Comment by wellton** [comment]
Helo, Openv_contrib has non-free software? =(

**Comment by hihozhou** [comment]
@wellton Extensions now have no mandatory requirements and require opencv_contrib,
you can try installing extensions again without opencv_contrib.
But if you need to call face recognition, you need to install opencv_contrib.

**Comment by MaleicAcid** [comment]
Hello.
