### ISSUE TITLE
Documentation in English

### ISSUE THREAD

**Issue by J4VMC** [hihozhou/php-opencv#12]
I can only see the documentation in zn_CH, is there any documentation in en_GB, en_US or en_EN?

**Comment by hihozhou** [comment]
Thank you for your feedback, I want to make efforts to perfect the function of the extension and Chinese documents, the next step to try to write English document. You can refer to official document, just be a c + + code into your familiar with PHP code.
See:[https://docs.opencv.org/master/de/d7a/tutorial_table_of_content_core.html](https://docs.opencv.org/master/de/d7a/tutorial_table_of_content_core.html)

**Comment by MaleicAcid** [comment]
Hello!
Thank you for your attention.
Rome was not built in a day.Please give us some time to perfect the documentation.

**Comment by ThaDaVos** [comment]
Sorry for commenting on an old issue, but any ETA on the english translations? The docs are partially translated currently and pretty hard to follow
