### ISSUE TITLE
我的系统是Ubuntu16 64位安装的时候出现问题了；

### ISSUE THREAD

**Issue by babywjw** [hihozhou/php-opencv#13]
我是根据你网站安装的，php是7.17 是Nginx
下载完opencv_contrib模块 
执行这个 git checkout 3.3.0-rc
出现了下面的情况：
![image](https://user-images.githubusercontent.com/3390383/32269045-37d2671e-bf2c-11e7-85f6-ce9be08a3d24.png)

**Comment by hihozhou** [comment]
你的opencv_contrib是怎么下载的？如果你是`git clone https://github.com/opencv/opencv_contrib.git`的话应该会有，如果没有，可以尝试切换到3.3版本`git checkout 3.3.0`。

**Comment by babywjw** [comment]
thanks，我已经按照你的意思去操作一遍，还是不行，我已经把我系统还原了，重新尝试了官网的一次流程 还是不行。我的系统是 阿里云官方 Ubuntu；
步骤是这个，只不过把3.3.0-rc变成了3.3.0
![1](https://user-images.githubusercontent.com/3390383/32306470-6d1c5972-bfb6-11e7-867d-ecc347386272.jpg)

结果是这样

![2](https://user-images.githubusercontent.com/3390383/32306520-d77facc4-bfb6-11e7-8052-f7f7dbc1e179.jpg)

**Comment by hihozhou** [comment]
那你就用3.3.1版本吧，这个版位问题只要是3.3+就可以。而那个checkout是opencv_contrib安装问题，你可以去搜下相关问题

**Comment by babywjw** [comment]
ok thanks.

**Comment by nduydoan** [comment]
I have problem when run cmd:
`make && make install`
This is attachment
![opencv_error-make-install](https://user-images.githubusercontent.com/10842067/33605855-eec74e90-d9ed-11e7-8a42-5f5790c75546.png)
Please help me.
Thanks.

**Comment by hihozhou** [comment]
@nduydoan What is your version of PHP？

**Comment by nduydoan** [comment]
@hihozhou  My PHP version 5.6.32

**Comment by hihozhou** [comment]
@nduydoan Sorry，the ext minimum support php7 version.

**Comment by nduydoan** [comment]
@hihozhou Thank your support. I will setup php7 version.

**Comment by nduydoan** [comment]
I have opencv.so file in modules directory
![extension-php ini](https://user-images.githubusercontent.com/10842067/33659193-eca03d74-dab1-11e7-84c2-2828092ca528.png)
Then, I run command:
`make test`
Results:
![make-test](https://user-images.githubusercontent.com/10842067/33659236-0426c54e-dab2-11e7-8b64-377fae185886.png)
But, when i run Obama.php file with content

> //Obama.php
use function CV\{ imread, imshow, waitkey, namedWindow};
> $im= imread('Obama.png');//load image
namedWindow('This is Obama id card',WINDOW_FULLSCREEN);//create window
imshow('This is Obama id card',$im);//show image on window
waitkey(0);

I have error:
![php-obama php](https://user-images.githubusercontent.com/10842067/33659361-826f176c-dab2-11e7-8bb5-138fa3c9a9f3.png)

Plz, help me.

**Comment by hihozhou** [comment]
@nduydoan Use commands `php -m  | grep opencv` to determine whether the opencv module is successfully loaded
