### ISSUE TITLE
LBPHFaceRecognizer: read/write/update/predictWithConfidence

### ISSUE THREAD

**Issue by morozovsk** [hihozhou/php-opencv#14]
You has created very good library but it is not ready for production without functions:
read, write, update, predictWithConfidence.

'confidence' is very important parameter for recognition.

[Example of recognition with confidence. What I want for demonstration for another people how your library works.](https://hsto.org/getpro/habr/post_images/bbf/414/0db/bbf4140db82be482546000312b6df06b.gif)

I have this script, it works but not good.
I have two photos for training: Will Ferrell and Chad Smith ...and two photos of Chad Smith for testing.

```
$faceRecognizer = \CV\Face\LBPHFaceRecognizer::create();

$data = ['will_ferrell.jpg' => 1, 'chad_smith.jpg' => 2];

$images = [];
$labels = [];
foreach ($data as $img => $label) {
    $cv_img = \CV\imread($img);
    $cv_img_gray = \CV\cvtColor($cv_img, \CV\COLOR_BGR2GRAY);
    \CV\equalizeHist($cv_img_gray, $cv_img_gray);
    $images[] = $cv_img_gray;
    $labels[] = $label;
}

$faceRecognizer->train($images, $labels);

$src = \CV\imread('test3.jpg');//chad smith
$gray = \CV\cvtColor($src, \CV\COLOR_BGR2GRAY);
\CV\equalizeHist($gray, $gray);
$faceLabel = $faceRecognizer->predict($gray);
var_export($faceLabel);//1 - wrong

$src = \CV\imread('test4.jpg');//chad smith
$gray = \CV\cvtColor($src, \CV\COLOR_BGR2GRAY);
\CV\equalizeHist($gray, $gray);
$faceLabel = $faceRecognizer->predict($gray);
var_export($faceLabel);//2 - right
```

will_ferrell.jpg (for training):
![will_ferrell.jpg](https://user-images.githubusercontent.com/1822063/34463410-eb39c12e-ee63-11e7-9305-77f6611bb793.jpg)
chad_smith.jpg (for training):
![chad_smith.jpg](https://user-images.githubusercontent.com/1822063/34463417-044cf258-ee64-11e7-811b-92ceacefa48e.jpg)
test3.jpg (**wrong** recognition):
![test3.jpg](https://user-images.githubusercontent.com/1822063/34463428-3ed65784-ee64-11e7-88be-cf47dd84c53c.jpg)
test4.jpg (right recognition):
![test4.jpg](https://user-images.githubusercontent.com/1822063/34463432-6d86e594-ee64-11e7-8417-a123051fc4f9.jpg)

Thanks again for the library and happy new year :)

**Comment by morozovsk** [comment]
I tried [openface](https://github.com/cmusatyalab/openface).
it also gives wrong result for test3.jpg with confidence 53%

**Comment by morozovsk** [comment]
I made read and write menthods. But I could not make predict method with returning by reference so made separate method predictConfidence:
https://github.com/morozovsk/php-opencv/blob/master/source/opencv2/face/opencv_facerec.cc

**Comment by hihozhou** [comment]
@morozovsk Thank you for your contribution. This extension has not been maintained for some reasons and will continue to develop in the future.

**Comment by morozovsk** [comment]
@hihozhou thank you very match for your answer and merging my pull request.
