### ISSUE TITLE
checking for opencv... too old

### ISSUE THREAD

**Issue by wellton** [hihozhou/php-opencv#2]
Hi, congratulations for your code =D

what is? checking for opencv... too old

I have the libcv-dev ahd libopencv-dev installed in my computer =(

**Comment by hihozhou** [comment]
@wellton sorry,I just saw your issues now.
This extension was developed on the basis of c++ OpenCV 3.2.0.
So the opencv version on your machine must be greater than 3.2.0.

And this extension uses the `pkg-config` command to test the opencv version of your machine.

You can use the command to see your version of opencv:

```bash
pkg-config --modversion opencv
```

**Comment by MaleicAcid** [comment]
now must be greater than 3.3.0.
