### ISSUE TITLE
编译phpopencv扩展的时候一直报错说opencv不存在

### ISSUE THREAD

**Issue by haidao1211** [hihozhou/php-opencv#21]
![qq 20180201171357](https://user-images.githubusercontent.com/26701778/35670426-86a437f2-0773-11e8-94c6-adff47d7442c.png)

![qq 20180201171019](https://user-images.githubusercontent.com/26701778/35670319-31b80228-0773-11e8-931d-c5db86f16f55.png)

您好！我已经安装成功了opencv，运行pkg-config --libs opencv 都能有正确的返回。但是编译php扩展的时候就提示opencv找不到。请问如何解决？
环境：centos+opencv3.3+php7.2
请问有交流php-opencv的QQ群吗？

**Comment by haidao1211** [comment]
![qq 20180202105805](https://user-images.githubusercontent.com/26701778/35714515-14177f7e-0808-11e8-8a32-d2aeff17c18a.png)
config.m4这里的判断语句能通过吗？我在命令行里输入pkg-config --exists opencv 返回的是0，看介绍是返回0就是存在的意思。但是这条语句返回0应该是通过不了的吧，不知道我理解的对不对。

**Comment by hihozhou** [comment]
暂时该扩展是使用系统的pkg-config去检测opencv是否安装的，
你可以尝试使用` pkg-config --modversion opencv`去查看opencv的版本
![image](https://user-images.githubusercontent.com/12164486/35715712-32ed8d42-080f-11e8-8435-a4b387257e0f.png)

**Comment by haidao1211** [comment]
可以显示版本。
问题已解决，是环境变量的问题。谢谢！

**Comment by hihozhou** [comment]
@haidao1211👌
