### ISSUE TITLE
copyTo not working

### ISSUE THREAD

**Issue by power-group** [hihozhou/php-opencv#29]
Hallo,
 the copyTo with mask function not working for me.

error log say:
PHP Warning:  CV\\Mat::copyTo() expects parameter 2 to be Pt\xa08R\x7f, object given in

how can i make a mask or is this a bug?

Gruß
power-group

**Comment by hihozhou** [comment]
Show me your code.

**Comment by power-group** [comment]
Hallo,

i have resolved the problem.
I make the mask with new Mat from the original image, not from the new.

nice extension. good job
