### ISSUE TITLE
Congratulations for 200 stars. It is time to start expansion! ;)

### ISSUE THREAD

**Issue by morozovsk** [hihozhou/php-opencv#31]
Now your project has 200 stars.
I woud like to help you to get much more. So I made:
1. project [php-opencv-examples](https://github.com/php-opencv/php-opencv-examples)
2. [docker image](https://hub.docker.com/r/morozovsk/php-opencv/)
3. [phpdoc file](https://github.com/php-opencv/php-opencv-examples/blob/master/phpdoc.php) for autocomplete and highlighting in PhpStorm and another IDEs

I think that is enough to start writing publications fot IT-sites like reddit.com, habr.com (russian) and medium.com
Today I've already post a link to reddit.com in [r/PHP](https://www.reddit.com/r/PHP/comments/8k6h8l/computer_vision_and_machine_learning_in_php_by/) and [r/opencv](https://www.reddit.com/r/opencv/comments/8k6hor/computer_vision_and_machine_learning_in_php_by/)
In the near future I'm going to write an post on habr.com. 
And later I'll translate it to english for medium.com

Happy 200 stars!

**Comment by MaleicAcid** [comment]
Hello there!
Glad you are also interested in this project. :)
I think 200 stars are indeed a small achievement. However, as far as this project is concerned, there are still many functions and modules that need to be improved, which also imposes higher requirements on developers.

I argue that if we want to further expand this project, we need to decide on a major development path. For example, we can divide functions into "used frequently and urgently needed", "frequently used but not eager to implement", "infrequently used", and so on. Then put them on schedule one by one.

I have written some simple features for this project, but now I have to leave for a while. Because in the coming months I will prepare my master's degree entrance exam. Although I may not submit code during this time, I will always come back to see it.
Good luck!

@hihozhou @morozovsk

**Comment by morozovsk** [comment]
I'm working on my plan:

- Code +

- Packages +
Because compiling from sourses is to mutch difficult for lot of people. I spent 2 days for first compilling php-opencv.

- Documentation +-
For documentation now I have only [phpdoc](https://github.com/php-opencv/php-opencv-examples/blob/master/phpdoc.php) and [official opencv documentation](https://docs.opencv.org/).
We don't have all features from opencv so it's difficult for user to search information aboute our functions in official opencv documentation.
I'd like to extend my phpdoc by information from official opencv documentation and after that generate markdown documentation for gitgub from phpdoc for all classes and methods what we have.

- Examples +-
Now I have only working with faces. But it is only one side of opencv. Users also need object categorisation and etc. I will know more about users wishes only after publication. So I think only faces are enought for start but mutch better to have second function like object categorisation for greater coverage of the user needs. I tried to use 'dnn::readNetFromDarknet()' but opencv doesn't support two layers from [that model](https://github.com/opencv/opencv/issues/11568). So now I'm working on it.

- Publication -+
After previous steps php-opencv will be complete for using by new users. But I afraid I will not have enought time so may be I will make publication without completion of all my steps.

Also I created organisation [php-opencv](https://github.com/php-opencv) for case when we will have lot of contributors. It will be easier to acept pull requests and support documentation, examples, packages etc. I made logo from opencv and php logos :)

https://github.com/ruby-opencv/ruby-opencv has 716 favorites and 144 forks so we have good chance to have more :)

**Comment by morozovsk** [comment]
I have written 3 new articles:
[habr](https://habr.com/post/358902/) - russian
[medium](https://medium.com/@morozovsk/computer-vision-and-machine-learning-in-php-using-the-opencv-library-3131fe9df94b) - english
[reddit](https://www.reddit.com/r/PHP/comments/8rtbk7/computer_vision_and_machine_learning_in_php_using/) - link to medium

**Comment by MaleicAcid** [comment]
Awesome article!

**Comment by morozovsk** [comment]
I found Chinese version of my article:
https://zhuanlan.zhihu.com/p/38462399

**Comment by morozovsk** [comment]
I'm sorry if I upset you somehow. You made a great library, a website and documentation.
I contributed to the library only about 1% of your work.

I created the php-opencv organization to increase the trust of users and to show that the library is mature enough.
morozovsk/php-opencv looks as personal project, php-opencv/php-opencv looks as community project.
Also I was hoping that we would get new contributors, but no one came :)

I thought you might be interested in knowing how someone uses your library. So I opened this Issue to share my results with you and @MaleicAcid to motivate all of us to continue developing.
If you don't like it - no problem. It's your personal project. You can do what you want. Furthermore. I think you can do more than all the other contributors together.

And thank you for acepting my pull request.

**Comment by morozovsk** [comment]
Also I would like to share information about [php-ffi](https://github.com/dstogov/php-ffi). It will be [part of PHP8](https://externals.io/message/102415).
It lets write code like this:
> <?php
$p = FFI::new("struct {int x,y;} [2]");
$p[0]->x = 5;
$p[1]->y = 10;
var_dump($p);

So writing and distribution of php-opencv will be easier, without compilation and through composer.
