### ISSUE TITLE
‘FacemarkLBF’ was not declared in this scope

### ISSUE THREAD

**Issue by Redominus** [hihozhou/php-opencv#32]
When making the php module i get this error
`/root/php-opencv/source/opencv2/face/opencv_facemarkLBF.cc:32:9: error: ‘FacemarkLBF’ was not declared in this scope
     Ptr<FacemarkLBF> Facemark;
`
Devtoolset used
gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)

**Comment by Redominus** [comment]
Nevemind solved by compiling the commit https://github.com/hihozhou/php-opencv/commit/5d7dc11e6d2647f9326619141adde7e31e56470a before adding Facemark

**Comment by morozovsk** [comment]
If your problem is solved you can close this ticket.
