### ISSUE TITLE
编译出错求解 弄了三天都没弄好 求解答！

### ISSUE THREAD

**Issue by BigDiaoKing** [hihozhou/php-opencv#38]
小弟系统是ubuntu 14.04.5  
cmake 版本为 3.2.2
gcc g++ 4.8 4.9 5都试过
sudo make 以后还是这样
安装流程是按照 http://phpopencv.org/zh-cn/ 上来的

下面是报错信息 求解，非常非常非常感谢！！

zeng@ubuntu:~/Desktop/OpenCV/opencv/build/php-opencv$ make && make install
/bin/bash /home/zeng/Desktop/OpenCV/opencv/build/php-opencv/libtool --mode=compile g++ -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/home/zeng/Desktop/OpenCV/opencv/build/php-opencv -DPHP_ATOM_INC -I/home/zeng/Desktop/OpenCV/opencv/build/php-opencv/include -I/home/zeng/Desktop/OpenCV/opencv/build/php-opencv/main -I/home/zeng/Desktop/OpenCV/opencv/build/php-opencv -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -I/usr/local/include/opencv -I/usr/local/include  -DHAVE_CONFIG_H  -g -O2   -c /home/zeng/Desktop/OpenCV/opencv/build/php-opencv/opencv.cc -o opencv.lo 
mkdir .libs
 g++ -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/home/zeng/Desktop/OpenCV/opencv/build/php-opencv -DPHP_ATOM_INC -I/home/zeng/Desktop/OpenCV/opencv/build/php-opencv/include -I/home/zeng/Desktop/OpenCV/opencv/build/php-opencv/main -I/home/zeng/Desktop/OpenCV/opencv/build/php-opencv -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -I/usr/local/include/opencv -I/usr/local/include -DHAVE_CONFIG_H -g -O2 -c /home/zeng/Desktop/OpenCV/opencv/build/php-opencv/opencv.cc  -fPIC -DPIC -o .libs/opencv.o
/bin/bash /home/zeng/Desktop/OpenCV/opencv/build/php-opencv/libtool --mode=compile g++ -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/home/zeng/Desktop/OpenCV/opencv/build/php-opencv -DPHP_ATOM_INC -I/home/zeng/Desktop/OpenCV/opencv/build/php-opencv/include -I/home/zeng/Desktop/OpenCV/opencv/build/php-opencv/main -I/home/zeng/Desktop/OpenCV/opencv/build/php-opencv -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -I/usr/local/include/opencv -I/usr/local/include  -DHAVE_CONFIG_H  -g -O2   -c /home/zeng/Desktop/OpenCV/opencv/build/php-opencv/source/opencv2/core/opencv_mat.cc -o source/opencv2/core/opencv_mat.lo 
mkdir source/opencv2/core/.libs
 g++ -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/home/zeng/Desktop/OpenCV/opencv/build/php-opencv -DPHP_ATOM_INC -I/home/zeng/Desktop/OpenCV/opencv/build/php-opencv/include -I/home/zeng/Desktop/OpenCV/opencv/build/php-opencv/main -I/home/zeng/Desktop/OpenCV/opencv/build/php-opencv -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -I/usr/local/include/opencv -I/usr/local/include -DHAVE_CONFIG_H -g -O2 -c /home/zeng/Desktop/OpenCV/opencv/build/php-opencv/source/opencv2/core/opencv_mat.cc  -fPIC -DPIC -o source/opencv2/core/.libs/opencv_mat.o
/home/zeng/Desktop/OpenCV/opencv/build/php-opencv/source/opencv2/core/opencv_mat.cc: In function ‘void opencv_mat_at(cv::Mat*, int*, long int, zval*, long int*, double*)’:
/home/zeng/Desktop/OpenCV/opencv/build/php-opencv/source/opencv2/core/opencv_mat.cc:87:66: error: ‘idx’ cannot appear in a constant-expression
         case CV_8SC2: return_schar_val = &mat->at<Vec<schar, 2>>(idx)[channel];
                                                                  ^
/home/zeng/Desktop/OpenCV/opencv/build/php-opencv/source/opencv2/core/opencv_mat.cc:87:71: error: ‘channel’ cannot appear in a constant-expression
       case CV_8SC2: return_schar_val = &mat->at<Vec<schar, 2>>(idx)[channel]; b
                                                                     ^
/home/zeng/Desktop/OpenCV/opencv/build/php-opencv/source/opencv2/core/opencv_mat.cc:87:78: error: an array reference cannot appear in a constant-expression
  case CV_8SC2: return_schar_val = &mat->at<Vec<schar, 2>>(idx)[channel]; break;
                                                                       ^
/home/zeng/Desktop/OpenCV/opencv/build/php-opencv/source/opencv2/core/opencv_mat.cc:87:78: error: template argument 2 is invalid
/home/zeng/Desktop/OpenCV/opencv/build/php-opencv/source/opencv2/core/opencv_mat.cc:87:48: error: parse error in template argument list
         case CV_8SC2: return_schar_val = &mat->at<Vec<schar, 2>>(idx)[channel];
                                                ^
/home/zeng/Desktop/OpenCV/opencv/build/php-opencv/source/opencv2/core/opencv_mat.cc:87:40: error: cannot resolve overloaded function ‘at’ based on conversion to type ‘schar* {aka signed char*}’
         case CV_8SC2: return_schar_val = &mat->at<Vec<schar, 2>>(idx)[channel];
                                        ^
/home/zeng/Desktop/OpenCV/opencv/build/php-opencv/source/opencv2/core/opencv_mat.cc:88:66: error: ‘idx’ cannot appear in a constant-expression
         case CV_8SC3: return_schar_val = &mat->at<Vec<schar, 3>>(idx)[channel];
                                                                  ^
/home/zeng/Desktop/OpenCV/opencv/build/php-opencv/source/opencv2/core/opencv_mat.cc:88:71: error: ‘channel’ cannot appear in a constant-expression
       case CV_8SC3: return_schar_val = &mat->at<Vec<schar, 3>>(idx)[channel]; b
                                                                     ^
/home/zeng/Desktop/OpenCV/opencv/build/php-opencv/source/opencv2/core/opencv_mat.cc:88:78: error: an array reference cannot appear in a constant-expression
  case CV_8SC3: return_schar_val = &mat->at<Vec<schar, 3>>(idx)[channel]; break;
                                                                       ^
/home/zeng/Desktop/OpenCV/opencv/build/php-opencv/source/opencv2/core/opencv_mat.cc:88:78: error: template argument 2 is invalid
/home/zeng/Desktop/OpenCV/opencv/build/php-opencv/source/opencv2/core/opencv_mat.cc:88:48: error: parse error in template argument list
         case CV_8SC3: return_schar_val = &mat->at<Vec<schar, 3>>(idx)[channel];
                                                ^
/home/zeng/Desktop/OpenCV/opencv/build/php-opencv/source/opencv2/core/opencv_mat.cc:88:40: error: cannot resolve overloaded function ‘at’ based on conversion to type ‘schar* {aka signed char*}’
         case CV_8SC3: return_schar_val = &mat->at<Vec<schar, 3>>(idx)[channel];
                                        ^
/home/zeng/Desktop/OpenCV/opencv/build/php-opencv/source/opencv2/core/opencv_mat.cc:89:66: error: ‘idx’ cannot appear in a constant-expression
         case CV_8SC4: return_schar_val = &mat->at<Vec<schar, 4>>(idx)[channel];
                                                                  ^
/home/zeng/Desktop/OpenCV/opencv/build/php-opencv/source/opencv2/core/opencv_mat.cc:89:71: error: ‘channel’ cannot appear in a constant-expression
       case CV_8SC4: return_schar_val = &mat->at<Vec<schar, 4>>(idx)[channel]; b
                                                                     ^
/home/zeng/Desktop/OpenCV/opencv/build/php-opencv/source/opencv2/core/opencv_mat.cc:89:78: error: an array reference cannot appear in a constant-expression
  case CV_8SC4: return_schar_val = &mat->at<Vec<schar, 4>>(idx)[channel]; break;
                                                                       ^
/home/zeng/Desktop/OpenCV/opencv/build/php-opencv/source/opencv2/core/opencv_mat.cc:89:78: error: template argument 2 is invalid
/home/zeng/Desktop/OpenCV/opencv/build/php-opencv/sour

**Comment by morozovsk** [comment]
ubuntu 14.04太旧了。 例如，Ubuntu 18.04具有gcc 7.3.0。

---

ubuntu 14.04 is too much old. For example Ubuntu 18.04 has gcc 7.3.0.

Installation on ubuntu 18.04 from packages (approximately 1 minute):
```
apt update && apt install -y wget && \
wget https://raw.githubusercontent.com/php-opencv/php-opencv-packages/master/opencv_3.4_amd64.deb && dpkg -i opencv_3.4_amd64.deb && rm opencv_3.4_amd64.deb && \
wget https://raw.githubusercontent.com/php-opencv/php-opencv-packages/master/php-opencv_7.2-3.4_amd64.deb && dpkg -i php-opencv_7.2-3.4_amd64.deb && rm php-opencv_7.2-3.4_amd64.deb && \
echo "extension=opencv.so" > /etc/php/7.2/cli/conf.d/opencv.ini
```
Installation via docker:
`docker run -it --name php-opencv morozovsk/php-opencv`

**Comment by morozovsk** [comment]
如果您不需要[dnn](https://github.com/php-opencv/php-opencv-examples)支持，可以通过命令安装旧版本的php-opencv：

> git checkout dev

  之前：

> phpize && ./configure --with-php-config=/usr/bin/php-config && make && make install

---

if you don't need [dnn](https://github.com/php-opencv/php-opencv-examples) support you can install old version of php-opencv by command:

> git checkout dev

 before:

> phpize && ./configure --with-php-config=/usr/bin/php-config && make && make install

**Comment by humSuperman** [comment]
[解决方法来自opencv作者]
尝试回滚到https://github.com/hihozhou/php-opencv/commit/2057bc05049e127819c9f84e79254cfa7033bad6 这个版本编译

**Comment by hihozhou** [comment]
编译问题,ubuntu14.0是可以安装的,最好还是直接使用[docker镜像](https://hub.docker.com/r/hihozhou/opencv/)进项编译安装,
