### ISSUE TITLE
使用快速开始代码，nginx报错502

### ISSUE THREAD

**Issue by humSuperman** [hihozhou/php-opencv#41]
编译安装php-opencv版本https://github.com/hihozhou/php-opencv/commit/2057bc05049e127819c9f84e79254cfa7033bad6 

use function CV\{ imread, imshow, waitKey};
$im = imread('Obama.png');
var_dump($im);
//可以打印出$im的对象信息
//使用imshow和waitKey nginx会报错502
//php-fpm日志记录进程死了
//imshow('This is Obama id card',$im);
//waitKey(0);

**Comment by hihozhou** [comment]
@humSuperman imshow和waitKey这些方式只支持cli形式的GUI方法，是不能用cgi形式调用的，
