### ISSUE TITLE
opencv2/dnn.hpp：No such file or directory

### ISSUE THREAD

**Issue by greatken999** [hihozhou/php-opencv#48]
In file included from /home/ken/phps/php-opencv/opencv.cc:46:
/home/ken/phps/php-opencv/source/opencv2/dnn/opencv_dnn.h:21:10: 致命错误：opencv2/dnn.hpp：No such file or directory

**Comment by morozovsk** [comment]
yes
it is a part of opencv library (not part of php-opencv) https://github.com/opencv/opencv/blob/master/modules/dnn/include/opencv2/dnn.hpp

**Comment by morozovsk** [comment]
Useful links:
[Installation on ubuntu](https://github.com/php-opencv/php-opencv-examples/wiki/Installation-on-ubuntu)
[installation via docker](https://github.com/php-opencv/php-opencv-examples/wiki/installation-via-docker)
[php-opencv-examples](https://github.com/php-opencv/php-opencv-examples)
[phpdoc](https://github.com/php-opencv/php-opencv-examples/blob/master/phpdoc.php)

**Comment by greatken999** [comment]
thanks @morozovsk

**Comment by hihozhou** [comment]
这部分代码已经回滚,现在应该没有这个问题了,dnn模块后续我会重新编写
