### ISSUE TITLE
扩展编译安装时,source下的opencv2报错

### ISSUE THREAD

**Issue by wilbur-oo** [hihozhou/php-opencv#51]
os:centos 7.2
opencv:编译安装的3.4.3
php:7.2.6
报错信息:
`/root/mysoft/git-project/php-opencv/source/opencv2/core/opencv_mat.cc: 在函数‘void opencv_mat_at(cv::Mat*, int*, long int, zval*, long int*, double*)’中:
/root/mysoft/git-project/php-opencv/source/opencv2/core/opencv_mat.cc:87:66: 错误：‘idx’不能出现在常量表达式中
         case CV_8SC2: return_schar_val = &mat->at<Vec<schar, 2>>(idx)[channel]; break;
                                                                  ^
/root/mysoft/git-project/php-opencv/source/opencv2/core/opencv_mat.cc:87:71: 错误：‘channel’不能出现在常量表达式中
         case CV_8SC2: return_schar_val = &mat->at<Vec<schar, 2>>(idx)[channel]; break;
                                                                       ^
/root/mysoft/git-project/php-opencv/source/opencv2/core/opencv_mat.cc:87:78: 错误：an array reference cannot appear in a constant-expression
         case CV_8SC2: return_schar_val = &mat->at<Vec<schar, 2>>(idx)[channel]; break;
                                                                              ^
/root/mysoft/git-project/php-opencv/source/opencv2/core/opencv_mat.cc:87:78: 错误：模板第 2 个参数无效
/root/mysoft/git-project/php-opencv/source/opencv2/core/opencv_mat.cc:87:48: 错误：模板实参表语法错误
         case CV_8SC2: return_schar_val = &mat->at<Vec<schar, 2>>(idx)[channel]; break;
                                                ^
/root/mysoft/git-project/php-opencv/source/opencv2/core/opencv_mat.cc:87:40: 错误：无法解析重载函数‘at’，基于向类型‘schar* {aka signed char*}’的转换
         case CV_8SC2: return_schar_val = &mat->at<Vec<schar, 2>>(idx)[channel]; break;
                                        ^
/root/mysoft/git-project/php-opencv/source/opencv2/core/opencv_mat.cc:88:66: 错误：‘idx’不能出现在常量表达式中
         case CV_8SC3: return_schar_val = &mat->at<Vec<schar, 3>>(idx)[channel]; break;
                                                                  ^
/root/mysoft/git-project/php-opencv/source/opencv2/core/opencv_mat.cc:88:71: 错误：‘channel’不能出现在常量表达式中
         case CV_8SC3: return_schar_val = &mat->at<Vec<schar, 3>>(idx)[channel]; break;
                                                                       ^
/root/mysoft/git-project/php-opencv/source/opencv2/core/opencv_mat.cc:88:78: 错误：an array reference cannot appear in a constant-expression
         case CV_8SC3: return_schar_val = &mat->at<Vec<schar, 3>>(idx)[channel]; break;
                                                                              ^
/root/mysoft/git-project/php-opencv/source/opencv2/core/opencv_mat.cc:88:78: 错误：模板第 2 个参数无效
/root/mysoft/git-project/php-opencv/source/opencv2/core/opencv_mat.cc:88:48: 错误：模板实参表语法错误
         case CV_8SC3: return_schar_val = &mat->at<Vec<schar, 3>>(idx)[channel]; break;
                                                ^
/root/mysoft/git-project/php-opencv/source/opencv2/core/opencv_mat.cc:88:40: 错误：无法解析重载函数‘at’，基于向类型‘schar* {aka signed char*}’的转换
         case CV_8SC3: return_schar_val = &mat->at<Vec<schar, 3>>(idx)[channel]; break;
                                        ^
/root/mysoft/git-project/php-opencv/source/opencv2/core/opencv_mat.cc:89:66: 错误：‘idx’不能出现在常量表达式中
         case CV_8SC4: return_schar_val = &mat->at<Vec<schar, 4>>(idx)[channel]; break;
                                                                  ^
/root/mysoft/git-project/php-opencv/source/opencv2/core/opencv_mat.cc:89:71: 错误：‘channel’不能出现在常量表达式中
         case CV_8SC4: return_schar_val = &mat->at<Vec<schar, 4>>(idx)[channel]; break;
                                                                       ^
/root/mysoft/git-project/php-opencv/source/opencv2/core/opencv_mat.cc:89:78: 错误：an array reference cannot appear in a constant-expression
         case CV_8SC4: return_schar_val = &mat->at<Vec<schar, 4>>(idx)[channel]; break;
                                                                              ^
/root/mysoft/git-project/php-opencv/source/opencv2/core/opencv_mat.cc:89:78: 错误：模板第 2 个参数无效
/root/mysoft/git-project/php-opencv/source/opencv2/core/opencv_mat.cc:89:48: 错误：模板实参表语法错误
         case CV_8SC4: return_schar_val = &mat->at<Vec<schar, 4>>(idx)[channel]; break;
                                                ^
/root/mysoft/git-project/php-opencv/source/opencv2/core/opencv_mat.cc:89:40: 错误：无法解析重载函数‘at’，基于向类型‘schar* {aka signed char*}’的转换
         case CV_8SC4: return_schar_val = &mat->at<Vec<schar, 4>>(idx)[channel]; break;
                                        ^
/root/mysoft/git-project/php-opencv/source/opencv2/core/opencv_mat.cc: 在函数‘void zim_opencv_mat_atIdx(zend_execute_data*, zval*)’中:
/root/mysoft/git-project/php-opencv/source/opencv2/core/opencv_mat.cc:517:16: 错误：‘nullptr’在此作用域中尚未声明
     int *idx = nullptr;
                ^
make: *** [source/opencv2/core/opencv_mat.lo] 错误 1
`

**Comment by morozovsk** [comment]
https://github.com/hihozhou/php-opencv/issues/49

**Comment by hihozhou** [comment]
可以尝试使用[opencv的docker镜像](https://hub.docker.com/r/hihozhou/opencv/)进行编译安装
