### ISSUE TITLE
/usr/local/php/bin/php: symbol lookup error: /usr/local/php/lib/php/extensions/no-debug-non-zts-20151012/opencv.so: undefined symbol: _ZN2cv6imreadERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi

### ISSUE THREAD

**Issue by YaoK4ik4i** [hihozhou/php-opencv#53]
Hello guys, after compiling, installing and opencv. so file were completed,  I running a small demo then appears the words below. I don't know how to fix this information. I have taken a long time search  the reason and this may be caused by  “dynamic libraries" .  Can you tell me what to do？System centos7 & gcc version 8.1.0 (GCC) 

编译安装和.so都完成以后 运行一个小demo出现下面信息不知如何修复，网上查了很久说是动态库优先级问题？ 系统centos7 gcc 8.1

/usr/local/php/bin/php: symbol lookup error: /usr/local/php/lib/php/extensions/no-debug-non-zts-20151012/opencv.so: undefined symbol: _ZN2cv6imreadERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi

**Comment by hihozhou** [comment]
@YaoK4ik4i 这里好像是C++报错。
具体centos下我没有进行过安装尝试，你可以参考一下这篇文章
https://blog.csdn.net/madril/article/details/80997793

**Comment by YaoK4ik4i** [comment]
> @YaoK4ik4i 这里好像是C++报错。
> 具体centos下我没有进行过安装尝试，你可以参考一下这篇文章
> https://blog.csdn.net/madril/article/details/80997793

ok，我去试试，不过我发现系统里还是有个3.4.4版的opencv在/usr/share/lib 里面，但是不清楚是不是这个导致的编译错误
