### ISSUE TITLE
Ooops ! no opencv detected in the system

### ISSUE THREAD

**Issue by RenatAkhatayev** [hihozhou/php-opencv#54]
x@x:/home/php-ext/open_cv/php-opencv# ./configure --with-php-config=/usr/bin/php-config --enable-debug
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php/20170718 -I/usr/include/php/20170718/main -I/usr/include/php/20170718/TSRM -I/usr/include/php/20170718/Zend -I/usr/include/php/20170718/ext -I/usr/include/php/20170718/ext/date/lib
checking for PHP extension directory... /usr/lib/php/20170718
checking for PHP installed headers prefix... /usr/include/php/20170718
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... gawk
checking for opencv support... yes, shared
checking for php debug... no
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking for pkg-config... found
checking for opencv... not found
**configure: error: Ooops ! no opencv detected in the system**

----------------------------
pkg-config --libs opencv
-L/usr/local/lib -lopencv_stitching -lopencv_superres -lopencv_videostab -lopencv_aruco -lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_dnn_objdetect -lopencv_dpm -lopencv_face -lopencv_photo -lopencv_fuzzy -lopencv_hfs -lopencv_img_hash -lopencv_line_descriptor -lopencv_optflow -lopencv_reg -lopencv_rgbd -lopencv_saliency -lopencv_stereo -lopencv_structured_light -lopencv_phase_unwrapping -lopencv_surface_matching -lopencv_tracking -lopencv_datasets -lopencv_text -lopencv_dnn -lopencv_plot -lopencv_xfeatures2d -lopencv_shape -lopencv_video -lopencv_ml -lopencv_ximgproc -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_flann -lopencv_xobjdetect -lopencv_imgcodecs -lopencv_objdetect -lopencv_xphoto -lopencv_imgproc -lopencv_core

**Comment by hihozhou** [comment]
@RenatAkhatayev The master branch corresponds to the opencv version of opencv4, `pkg-config --libs opencv4`, please use 3.3+ version to compile and install https://github.com/hihozhou/php-opencv/releases/tag/3.3.0

**Comment by RenatAkhatayev** [comment]
@hihozhou Thank! the project was successfully compiled, but now such an error occurs

PHP Warning:  PHP Startup: Unable to load dynamic library '/home/php-ext/open_cv/php-opencv/modules/opencv.so' (tried: /home/php-ext/open_cv/php-opencv/modules/opencv.so (/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/local/lib/libopencv_stitching.so.3.4)), /usr/lib/php/20170718//home/php-ext/open_cv/php-opencv/modules/opencv.so.so (/usr/lib/php/20170718//home/php-ext/open_cv/php-opencv/modules/opencv.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

**Comment by hihozhou** [comment]
Check with the ` ls /usr/local/lib/ | grep libopencv_stitching.so` command

**Comment by RenatAkhatayev** [comment]
@hihozhou 
`ls /usr/local/lib/ | grep libopencv_stitching.so`
libopencv_stitching.so
libopencv_stitching.so.3.2
libopencv_stitching.so.3.2.0
libopencv_stitching.so.3.4
libopencv_stitching.so.3.4.1
libopencv_stitching.so.4.0
libopencv_stitching.so.4.0.1

**Comment by hihozhou** [comment]
@RenatAkhatayev Try this commands:
```bash
sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf' 
ldconfig
```

**Comment by mohamedyasser** [comment]
i have the same issue any solution

**Comment by mohamedyasser** [comment]
> @RenatAkhatayev Try this commands:
> 
> ```shell
> sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf' 
> ldconfig
> ```

not working

**Comment by hihozhou** [comment]
@mohamedyasser If `make` and `make test` are successful, check your environment and configuration for correctness based on error prompts
