### ISSUE TITLE
tests/videoCapture.phpt dosn't work in docker

### ISSUE THREAD

**Issue by morozovsk** [hihozhou/php-opencv#55]
[tests/videoCapture.phpt dosn't work in docker](https://travis-ci.org/hihozhou/php-opencv/builds/452219744#L680)
[It breaks continuous-integration/travis-ci](https://travis-ci.org/hihozhou/php-opencv/builds/452219744?utm_source=github_status&utm_medium=notification)
[All commits are tagged as "All checks have failed"](https://github.com/hihozhou/php-opencv/commits/master)

**Comment by hihozhou** [comment]
I also found this problem, can you judge whether it is docker in php?
