### ISSUE TITLE
透视变换有对应的方法吗？

### ISSUE THREAD

**Issue by A123asdo11** [hihozhou/php-opencv#61]
您好：
 想做透视变换，不知道扩展里有没有相应的方法？
![image](https://user-images.githubusercontent.com/9299509/53245070-aed43980-36e7-11e9-883c-35300e7e479f.png)

**Comment by hihozhou** [comment]
可以，明天加一下

**Comment by hihozhou** [comment]
不好意思，之前有点忙，已经补上`CV\getPerspectiveTransform`和`CV\warpPerspective`方法在master分支上，具体使用可以查看demo https://github.com/phpopencv/tutorial-demo/blob/master/ImgProc/warpPerspective/warpPerspective.php

**Comment by A123asdo11** [comment]
@hihozhou 谢谢谢谢太好了！
我这些天也用c++写了下demo， 遇到一个问题， 当使用 getPerspectiveTransform 的时候，需要传 $srcPoints 和 $dstPoints。 srcPoints可以通过在图像上拖动选框来标定4个点， 但dstPoints 如何确定就不知道了 （要处理的不是一种宽高比的图像，比如身份证、书本等，主要是为了让用户自己能矫正图像），您知道怎么确定这个dstPoints？

**Comment by hihozhou** [comment]
@A123asdo11 这个我当时想写识别身份证程序也没有想好这个，如果实现了分享一下经验哈

**Comment by hihozhou** [comment]
其实dstPoints倒还容易，因为需要是正矩形，所以`左上角`的`y坐标`和`右上角`的`y坐标`相同，`左上角`的x坐标和左下角的x坐标相同，只要固定srcPoint的两点，让另外两点坐标x或y对其就可以

**Comment by A123asdo11** [comment]
@hihozhou  抱歉最近比较忙 也没看github。
对我这边来说，srcPoints 容易，直接在手机上拖动选框就能标出4个点， 就想 用 “扫描全能王” 拖动裁剪框那样。  但 dstPoints 就比较难了， 如果不能很好的知道dstImage的宽高比，那么透视矫正后的图，就容易比例失调。
