### ISSUE TITLE
dll win x64 compile?

### ISSUE THREAD

**Issue by tarasfrompir** [hihozhou/php-opencv#64]
When I compile .dll all .obj files appear along this path - C: \ www \ php-sdk-binary-tools \ phpdev \ vc15 \ x64 \ php \ x64 \ Release_TS \ ext \ php-opencv-master instead of C: \ www \ php-sdk-binary-tools \ phpdev \ vc15 \ x64 \ php \ x64 \ Release_TS \ ext \ php-opencv-master / source / opencv2 / core. And accordingly, an error appears about the wrong path to the obj file. What am I doing wrong...?

Screenshoot - https://pastenow.ru/bcf16fb861442361370f7af6b7756ecb

**Comment by hihozhou** [comment]
.obj is the target file, it is your source program compiled program compiled generated.During the compilation of the output directory see php_opencv.dll file?

**Comment by tarasfrompir** [comment]
This error prevents you from completing the library compilation. - 
LINK: fatal error LNK1181: cannot open the input file "C: \ www \ php-sdk-binary-tools \ phpdev \ vc15 \ x64 \ php \ x64 \ Release_TS \ ext \ php-opencv-master \ source \ opencv2 \ core \ hal \ opencv_interface.obj "
NMAKE: fatal error U1077: "C: \ Program Files (x86) \ Microsoft Visual Studio \ 2017 \ Professional \ VC \ Tools \ MSVC \ 14.16.27023 \ bin \ HostX64 \ x64 \ link.exe": returned code "0x49d"
Stop
All .obj files has not tree - [https://pastenow.ru/bcf16fb861442361370f7af6b7756ecb](url)
