### ISSUE TITLE
Where should i install php-opencv in my Laravel project for usage in it?

### ISSUE THREAD

**Issue by oennm** [hihozhou/php-opencv#65]
I'm working on a Laravel project and wish to know where should i install php-opencv in the project folder because i can't use the functions otherwise.

**Comment by hihozhou** [comment]
This is a PHP extension, you need to compile installation, loading, at the beginning of the request. You can use php.ini configuration switches, this and the laravel and has nothing to do, you can use under the cli or cgi, but some GUI function can only be cut using the cli, such as waitkey, imshow function.

**Comment by oennm** [comment]
Thanks for the guide. I figure out the problem, it was because i'm running my Laravel project inside a Docker container and php-opencv extension was not declared and neither was OpenCV itself.

**Comment by oennm** [comment]
Rookie mistake i know but i'm learning.
