### ISSUE TITLE
文档有很多页面都是404

### ISSUE THREAD

**Issue by nzing** [hihozhou/php-opencv#7]
http://phpopencv.org/zh-cn/docs/mat-mask-operations.html
http://phpopencv.org/zh-cn/docs/mat-mask-operations.html
http://phpopencv.org/zh-cn/docs/mat-operations.html
http://phpopencv.org/zh-cn/docs/basic-geometric-drawing.html
……

**Comment by hihozhou** [comment]
@nzing 目前很多文档还在待写当中,会努力完善,谢谢支持
