### ISSUE TITLE
你好，请问一下 GaussianBlur Canny  findContours 这个三个方法能否正常使用

### ISSUE THREAD

**Issue by lmafwo** [hihozhou/php-opencv#70]
目前是使用 利用opencv库中提供的边界查找函数(cv2.findContours)提取单片拼图边缘轨迹并构造成一个二维矩阵（算子）
利用 高斯模糊算子（cv2.GaussianBlur）和 Canny边缘检测算子（cv2.Canny）对背景图进行处理，凸显出拼图在图片中的边缘

**Comment by morozovsk** [comment]
It already exits:
https://github.com/hihozhou/php-opencv/search?q=GaussianBlur&unscoped_q=GaussianBlur
I added description to [phpdoc](https://github.com/php-opencv/php-opencv-examples/blob/master/phpdoc.php#L864) from [there](https://github.com/hihozhou/php-opencv-ide-helper/search?q=GaussianBlur&unscoped_q=GaussianBlur).

**Comment by hihozhou** [comment]
@lmafwo 可以
