### ISSUE TITLE
How to use the docker image

### ISSUE THREAD

**Issue by spartyboy** [hihozhou/php-opencv#72]
how do i create my own open cv application after pulling the docker image, because i have being unable to download open cv using ubuntu 19.04

**Comment by spartyboy** [comment]
am using laravel framework and i have never used docker also so how do i embed it in my framework, please

**Comment by hihozhou** [comment]
Try using the installation tool https://github.com/phpopencv/installer

```bash
composer global require "phpopencv/installer"
```

**Comment by spartyboy** [comment]
how fo i download the opencv on ubuntu 19.04 because i keep getting errors while using the official documentation on phpopencv when i get to the make -j6 some cp files would be showing deprecaten or found errors at some line

**Comment by spartyboy** [comment]
is there any other way to get around that issue

**Comment by hihozhou** [comment]
Direct use of docker images

```bash
docker pull hihozhou/php-opencv
```

**Comment by spartyboy** [comment]
no i am talking of opencv itself i keep getting issues installing it and i dont know how to use the docker image though i have pulled it and used the docker run command, i need it for face recognition and i need to modify the recognition syntax

**Comment by spartyboy** [comment]
the command line interface method keeps giving me issues
