### ISSUE TITLE
Class 'CV\Face\LBPHFaceRecognizer' not found

### ISSUE THREAD

**Issue by paulohlimamaia** [hihozhou/php-opencv#82]
I'm getting the title error everytime i use the bellow code:

`
$faceRecognizer = LBPHFaceRecognizer::create();
`

I always get:

`Symfony\Component\Debug\Exception\FatalThrowableError  : Class 'CV\Face\LBPHFaceRecognizer' not found`

Another functions, classes and variables works fine.

Functions and Classes that worked fine are the following:
```
use CV\CascadeClassifier;
use function CV\imread;
use CV\Mat;
use CV\Size;

use const CV\{
    COLOR_BGR2GRAY, CASCADE_SCALE_IMAGE
};
use function CV\{
    cvtColor, equalizeHist
};
```

I tried with **OpenCV** version **4.9.1**  and version **3.4.2** 
(The older OpenCV version i used with the following release: PHP-OpenCV [3.3.0](https://github.com/hihozhou/php-opencv/releases/tag/3.3.0))

It's a name issue maybe? Am i doing something wrong? Maybe it has to do with OpenCV Contrib packages? I'm clueless.

**Comment by paulohlimamaia** [comment]
I detected that the opencv_contrib was not installed correctly.
This is most certanly the issue here. Just reinstalling OpenCV and confirming this and will close the issue.

**Comment by fherryfherry** [comment]
Same issue here

**Comment by fherryfherry** [comment]
![image](https://user-images.githubusercontent.com/6733315/62134126-26973780-b30a-11e9-918c-d4abdf508709.png)
But the open cv module detail doesn't show anything

**Comment by paulohlimamaia** [comment]
As i thought the problem was in the OpenCV_Contrib installation.

@fherryfherry you need to follow the instructions on [this](https://phpopencv.org/docs/install.html) page except on the installation of php-opencv, for that you want to use the [3.3.0](https://github.com/hihozhou/php-opencv/releases/tag/3.3.0) version of php-opencv. Then you can resume following the instructions of [that](https://phpopencv.org/docs/install.html) page and the function will work.

I'll be closing this issue because it was resolved.
